# Generated by Django 5.2.13 on 2026-04-11 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secteur', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('rayon_km', models.IntegerField(default=5)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('running', 'En cours'), ('done', 'Terminée'), ('error', 'Erreur')], default='draft', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('launched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Variables disponibles : {nom}, {ville}, {secteur}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.CharField(blank=True, default='', max_length=300)),
                ('ville', models.CharField(blank=True, default='', max_length=100)),
                ('telephone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('has_website', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('contacted', 'Contacté'), ('replied', 'Répondu'), ('ignored', 'Ignoré')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospects', to='prospection.campaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prospection.emailtemplate')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='prospection.prospect')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
