# Generated by Django 5.2.13 on 2026-06-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(help_text='Variables disponibles : {nom}, {ville}, {secteur}, {website}'),
        ),
    ]
