# Generated by Django 5.2.13 on 2026-06-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospection', '0002_alter_emailtemplate_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='social_platform',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='prospect',
            name='social_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(help_text='Variables disponibles : {nom}, {ville}, {secteur}, {website}, {social}, {social_platform}'),
        ),
    ]
