# Generated by Django 5.2.13 on 2026-06-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospection', '0003_prospect_social_platform_prospect_social_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospect',
            name='social_platform',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='social_url',
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(help_text='Variables disponibles : {nom}, {ville}, {secteur}, {website}'),
        ),
    ]
